static public class LevelID
{
    public const int      
        Cortex_Power                    = 0x03,              
        unused_Cavern_Level             = 0x04,                       
        Generator_Room                  = 0x05,                
        Heavy_Machinery                 = 0x06,                 
        Toxic_Waste                     = 0x07,             
        Pinstripe_Boss_4                = 0x08,                    
        N_Sanity_Beach                  = 0x09,                 
        Papu_Papu_Boss_1                = 0x0a,                          
        Jungle_Rollers                  = 0x0c,                      
        Boulders                        = 0x0e,          
        Upstream                        = 0x0f,                 
        Hog_Wild                        = 0x11,          
        The_Great_Gate                  = 0x12,                
        Boulder_Dash                    = 0x13,              
        Road_to_Nowhere                 = 0x14,                 
        Rolling_Stones                  = 0x15,                
        The_High_Road                   = 0x16,               
        Ripper_Roo_Boss_2               = 0x17,                     
        Up_The_Creek                    = 0x18,              
        Map_Main_Menu_Title_Sequence    = 0x19,                                
        Native_Fortress                 = 0x1a,                 
        Nitrus_Brio_Boss_5              = 0x1b,                      
        Temple_Ruins                    = 0x1c,              
        Jaws_of_Darkness                = 0x1d,                  
        Whole_Hog                       = 0x1e,           
        Dr_Neo_Cortex_Boss_6            = 0x1f,                         
        The_Lost_City                   = 0x20,               
        Koala_Kong_Boss_3               = 0x21,                     
        Stormy_Ascent                   = 0x22,                        
        Sunset_Vista                    = 0x23,              
        Bonus_Round_Tawna__short_version= 0x24,                                     
        Bonus_Round_Nitrus_Brio         = 0x25,                           
        Bonus_Round_currently_unknown   = 0x26,                                       
        Lights_Out                      = 0x28,            
        The_Lab                         = 0x29,         
        Fumbling_in_the_Dark            = 0x2a,                             
        The_Great_Hall                  = 0x2c,                
        Level_Completion_Screen         = 0x2d,                         
        Slippery_Climb                  = 0x2e,                       
        Bonus_Round_Tawna_long_version  = 0x33,                                    
        Bonus_Round_Dr_Neo_Cortex       = 0x34,                                   
        Castle_Machinery                = 0x37,                  
        Intro                           = 0x38,        
        Ending                          = 0x39;    
    
    
}